[package]
name = "exms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = { version = "1.9.3", features = ["serde-1"] }
serde = { version = "1.0.164", features = ["derive"] }
colored = "2.0.0"
prettytable = "0.10.0"
serde_json = "1.0.97"
toml = "0.7.4"
assert_approx_eq = "1.1.0"
