[students]
"Abad Martinez, Jose" = 7.6
"Amat Canales, Laura" = 3.25
"Arnal Martínez, Oxel" = 7.55
"Avilés Martínez, Pablo" = 3.65
"Beltrán Peris, Joan" = 2.8
"Blanes Álvarez, Álvaro" = 1.75
"Bleda Miranda, Alberto" = 7.35
"Bosch i Navarro, Sheila" = 3.0
"Campos Blanco, Berta" = 7.4
"Carrascosa Alarcón, Raúl" = 2.7
"Casells Pallás, María" = 4.0
"Castelló Sal, Federico Jorge" = 3.0
"Cebrian Palud, Gaizka" = 2.1
"Cervero Ruiz, Oriol" = 4.0
"Corell Fernández de Córdova, María Magdalena" = 3.75
"Correa Lleó, Gonzalo" = 4.15
"Dominguez Martinez, Carlos Eduardo" = 5.4
"Esteban Bernat, Alejandro" = 5.35
"Flors Fernández, Rocío" = 1.85
"Fuentes Viñegla, Alejandra" = 5.15
"Galdámez Fayos, Diego" = 0.75
"Garcia Ballester, Luis" = 0.0
"Garcia Gayet, Maria del Pilar" = 2.9
"García Golvano, Raquel" = 3.65
"Gil-Pérez Torres, Daniel" = 4.0
"Girona Server, Francisco José" = 3.0
"Gozalbes Fresquet, Lucía" = 3.0
"Heredia Riascos, Juan Francisco" = 5.0
"Jiménez Bou, Óscar" = 2.75
"Jordán Furió, Miguel Ángel" = 5.6
"Kostiuk, Illia" = 7.25
"Kruger Arnal, Claudia" = 4.0
"Linés Núñez, Gonzalo" = 2.1
"Lopez Palomar, Jose" = 4.25
"Marrades Lozano, Joan" = 3.25
"Martínez Lax, Manuel Reyes" = 7.5
"Martínez Moreno, Alejandro" = 5.55
"Mayoral Baños, Daniel" = 0.8
"Mehdi Telmakou, Khouloud" = 0.25
"Mesa Moyano, Rubén" = 4.4
"Monraval Pardo, Lucía" = 7.0
"Montero Mora, Javier" = 3.25
"Monzón Soto, Raúl Eduardo" = 1.0
"Morán Brito, Orlyn Leonel" = 1.5
"Motilla Pérez, Carlos" = 7.0
"Muñoz Giménez, Salomé" = 5.0
"Navarro Martínez, Vicente" = 4.15
"Pascual Rodríguez, Alejandro" = 0.75
"Pelufo Solar, Jorge" = 6.0
"Pérez Fernández, Lucía" = 3.55
"Pérez García, José Julio" = 2.8
"Romero Polo, Jaime" = 2.2
"Sebastià Mateo, Maria" = 2.85
"Sánchez Mendoza, Jorge" = 5.25
"Tanveer, Muhammad Abdullah" = 8.15
"Vega Espacio, Lucas" = 1.5
"Vilar Milcovici, Alejandro David" = 4.55
"Zamora Calomarde, José Enrique" = 6.25
